// Site Eletropostos Brasil: home, mapa, estações por estado/cidade, página por eletroposto, redes, guia, FAQ, dados, cadastro.
import fs from 'fs';
const DOMAIN = process.env.SITE_DOMAIN || '';
const ROOT = DOMAIN ? '' : (process.env.SITE_ROOT ?? '/eletropostos-brasil');
const BASE = DOMAIN ? `https://${DOMAIN}` : `https://spartanti.github.io${ROOT}`;
const API = 'https://eletropostos-api-production.up.railway.app';
const data = JSON.parse(fs.readFileSync('stations.json', 'utf8'));
const stations = data.stations;
const UF = { AC:'Acre',AL:'Alagoas',AP:'Amapá',AM:'Amazonas',BA:'Bahia',CE:'Ceará',DF:'Distrito Federal',ES:'Espírito Santo',GO:'Goiás',MA:'Maranhão',MT:'Mato Grosso',MS:'Mato Grosso do Sul',MG:'Minas Gerais',PA:'Pará',PB:'Paraíba',PR:'Paraná',PE:'Pernambuco',PI:'Piauí',RJ:'Rio de Janeiro',RN:'Rio Grande do Norte',RS:'Rio Grande do Sul',RO:'Rondônia',RR:'Roraima',SC:'Santa Catarina',SP:'São Paulo',SE:'Sergipe',TO:'Tocantins' };
const slug = s => String(s || '').normalize('NFD').replace(/[̀-ͯ]/g, '').toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
const esc = s => String(s ?? '').replace(/[&<>"]/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c]));
const kw = c => c.kw ? `${Number.isInteger(c.kw) ? c.kw : c.kw.toFixed(1)} kW` : '';
const fmt = n => Number(n).toLocaleString('pt-BR');
const today = new Date().toISOString().slice(0, 10);
const km = (a, b) => { const R = 6371, d = Math.PI / 180, x = (b.lon - a.lon) * d * Math.cos((a.lat + b.lat) / 2 * d), y = (b.lat - a.lat) * d; return R * Math.sqrt(x * x + y * y); };
const stPath = s => `${ROOT}/estacao/${slug(s.city || s.uf)}-${slug(s.name).slice(0, 50)}-${s.id.replace(/[^a-z0-9]/gi, '')}.html`;
const MAPLIBRE = `<link href="https://unpkg.com/maplibre-gl@4.7.1/dist/maplibre-gl.css" rel="stylesheet"><script src="https://unpkg.com/maplibre-gl@4.7.1/dist/maplibre-gl.js"></script>`;

const CSS = `
:root{--azul:#1565C0;--azul2:#0B3D91;--claro:#DCE8FF;--laranja:#EF6C00;--fundo:#F4F7FC;--texto:#16202E;--cinza:#4A5666;--verde:#2E7D32;--borda:#DDE5F0}
*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;font-family:Inter,system-ui,-apple-system,"Segoe UI",Roboto,sans-serif;color:var(--texto);background:var(--fundo);line-height:1.55}
a{color:var(--azul)}img{max-width:100%}h1,h2,h3{line-height:1.2}h2{color:var(--azul2);font-size:1.7rem;margin:44px 0 14px}
header{background:#fff;border-bottom:1px solid var(--borda);position:sticky;top:0;z-index:20}.nav{max-width:1120px;margin:0 auto;display:flex;align-items:center;gap:18px;padding:10px 16px}
.nav .logo{display:flex;align-items:center;gap:10px;font-weight:800;color:var(--azul2);text-decoration:none;font-size:1.1rem}.nav .logo img{width:36px;height:36px;border-radius:10px}
.nav nav{margin-left:auto;display:flex;gap:16px;align-items:center}.nav nav a{text-decoration:none;color:var(--cinza);font-weight:600}
.btn{display:inline-flex;align-items:center;gap:8px;background:var(--azul);color:#fff!important;padding:12px 20px;border-radius:12px;text-decoration:none;font-weight:700;border:0;cursor:pointer}.btn.l{background:var(--laranja)}.btn.o{background:#fff;color:var(--azul)!important;border:2px solid var(--azul)}.btn.s{padding:8px 14px;font-size:.9rem}
main{max-width:1120px;margin:0 auto;padding:20px 16px}
.hero{display:grid;grid-template-columns:1.15fr .85fr;gap:36px;align-items:center;padding:30px 0 10px}.hero h1{font-size:2.6rem;color:var(--azul2);margin:0 0 14px}.hero p.lead{font-size:1.2rem;color:var(--cinza);margin:0 0 18px}
.badges{display:flex;gap:8px;flex-wrap:wrap;margin:0 0 18px}.badge{background:#fff;border:1px solid var(--borda);border-radius:50px;padding:6px 12px;font-size:.9rem;font-weight:600;color:var(--azul2)}
.phone{justify-self:center;width:300px;padding:12px;background:#0B1220;border-radius:40px;box-shadow:0 30px 60px rgba(11,61,145,.28)}.phone img{border-radius:28px;display:block;width:100%}
.stats{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:14px;margin:26px 0}.stat{background:#fff;border-radius:16px;padding:18px;text-align:center;box-shadow:0 2px 12px rgba(0,0,0,.05)}.stat b{display:block;font-size:2rem;color:var(--azul)}
.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(250px,1fr));gap:16px}.card{background:#fff;border-radius:16px;padding:18px;box-shadow:0 2px 12px rgba(0,0,0,.05)}.card h3{margin:0 0 6px;color:var(--azul2);font-size:1.05rem}
.feat .ic{width:44px;height:44px;border-radius:12px;background:var(--claro);display:flex;align-items:center;justify-content:center;margin-bottom:10px;color:var(--azul);font-size:1.4rem}
.chip{display:inline-block;background:var(--claro);color:var(--azul2);border-radius:8px;padding:2px 8px;font-size:.85rem;margin:2px 4px 2px 0;font-weight:600}.chip.ac{background:#FFE3C4;color:#5C2A00}.tag{font-size:.7rem;padding:1px 6px;border-radius:4px;color:#fff;background:var(--azul);margin-left:4px}.tag.ac{background:var(--laranja)}
table{width:100%;border-collapse:collapse;background:#fff;border-radius:12px;overflow:hidden}td,th{padding:10px 12px;border-bottom:1px solid #EEF2F8;text-align:left;vertical-align:top}th{background:var(--claro);color:var(--azul2)}
.steps{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:16px;counter-reset:s}.step{background:#fff;border-radius:16px;padding:20px;position:relative}.step:before{counter-increment:s;content:counter(s);position:absolute;top:-14px;left:16px;background:var(--laranja);color:#fff;font-weight:800;width:32px;height:32px;border-radius:50%;display:flex;align-items:center;justify-content:center}
.shots{display:flex;gap:14px;overflow-x:auto;padding:12px 4px;scroll-snap-type:x mandatory}.shots img{height:440px;border-radius:18px;box-shadow:0 8px 24px rgba(0,0,0,.12);scroll-snap-align:start}
.ufs{display:flex;flex-wrap:wrap;gap:8px}.ufs a{background:#fff;border:1px solid var(--borda);border-radius:10px;padding:8px 12px;text-decoration:none;color:var(--azul2);font-weight:600}
details{background:#fff;border-radius:12px;padding:12px 16px;margin:8px 0}summary{cursor:pointer;font-weight:700;color:var(--azul2)}
.crumb{font-size:.9rem;color:var(--cinza);margin:0 0 8px}.map{height:420px;border-radius:16px;margin:12px 0}.map.big{height:76vh}
.stlist .card{display:grid;grid-template-columns:1fr auto;gap:10px}.stlist .card .go{align-self:center}
footer{background:#0B1220;color:#B8C4D6;margin-top:50px}.foot{max-width:1120px;margin:0 auto;padding:36px 16px;display:grid;grid-template-columns:2fr 1fr 1fr 1fr;gap:24px;font-size:.92rem}.foot a{color:#fff;text-decoration:none}.foot h4{color:#fff;margin:0 0 8px}.foot .copy{grid-column:1/-1;border-top:1px solid #223;padding-top:14px;font-size:.82rem}
.sticky{position:fixed;bottom:0;left:0;right:0;background:#fff;border-top:1px solid var(--borda);padding:10px 16px;display:none;z-index:30}
@media(max-width:820px){.hero{grid-template-columns:1fr}.hero h1{font-size:1.9rem}.nav nav{display:none}.foot{grid-template-columns:1fr 1fr}.sticky{display:flex;justify-content:center}body{padding-bottom:70px}}
`;
const NAV = `<nav><a href="${ROOT}/mapa.html">Mapa</a><a href="${ROOT}/estacoes/">Estados</a><a href="${ROOT}/redes/">Redes</a><a href="${ROOT}/guia-tomadas.html">Guia</a><a href="${ROOT}/dados.html">Dados</a><a href="${ROOT}/cadastrar.html">Cadastrar</a><a href="${ROOT}/#baixar" class="btn s">Baixar o app</a></nav>`;
function page({ title, desc, path, body, jsonld, extraHead = '' }) {
  return `<!DOCTYPE html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>${esc(title)}</title><meta name="description" content="${esc(desc)}"><link rel="canonical" href="${BASE}${path}">
<meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(desc)}"><meta property="og:image" content="${BASE}/assets/og.png"><meta property="og:type" content="website"><meta name="twitter:card" content="summary_large_image">
<link rel="icon" href="${ROOT}/assets/icon-512.png"><link rel="preconnect" href="https://tiles.openfreemap.org"><style>${CSS}</style>${extraHead}${jsonld ? `<script type="application/ld+json">${JSON.stringify(jsonld)}</script>` : ''}</head>
<body><header><div class="nav"><a class="logo" href="${ROOT}/"><img src="${ROOT}/assets/icon-512.png" alt="">Eletropostos Brasil</a>${NAV}</div></header>
<main>${body}</main>
<footer><div class="foot"><div><h4>Eletropostos Brasil</h4>App gratuito para encontrar onde carregar seu carro elétrico no Brasil, com ${fmt(stations.length)} eletropostos, planejador de viagem e relatos da comunidade. Desenvolvido e gerenciado pela <a href="https://spartanti.com.br">Spartan TI</a>.</div>
<div><h4>Explorar</h4><a href="${ROOT}/mapa.html">Mapa</a><br><a href="${ROOT}/estacoes/">Estações por estado</a><br><a href="${ROOT}/redes/">Redes e operadores</a><br><a href="${ROOT}/guia-tomadas.html">Guia de tomadas</a><br><a href="${ROOT}/dados.html">Dados do mercado</a></div>
<div><h4>Participe</h4><a href="${ROOT}/#baixar">Baixar o app</a><br><a href="${ROOT}/cadastrar.html">Cadastrar eletroposto</a><br><a href="${ROOT}/perguntas-frequentes.html">Perguntas frequentes</a><br><a href="${ROOT}/privacidade.html">Privacidade</a></div>
<div><h4>Contato</h4><a href="mailto:admin@spartanti.com.br">admin@spartanti.com.br</a><br><a href="https://wa.me/5527992557140">WhatsApp +55 27 99255-7140</a></div>
<div class="copy">Dados: © Open Charge Map contributors (CC BY 4.0) · © OpenStreetMap contributors (ODbL) · cadastros da comunidade · status via Carregados. Mapa: MapLibre + OpenFreeMap. Base atualizada em ${data.generated}. As informações podem mudar; confirme no local.</div></div></footer>
<div class="sticky"><a class="btn l" href="${ROOT}/#baixar">⚡ Baixar o app grátis</a></div>
</body></html>`;
}
const connChips = s => s.conns.map(c => `<span class="chip ${c.dc ? '' : 'ac'}">${esc(c.t)}${kw(c) ? ' ' + kw(c) : ''}${c.q > 1 ? ' ×' + c.q : ''}<span class="tag ${c.dc ? '' : 'ac'}">${c.dc ? 'RÁPIDA' : 'LENTA'}</span></span>`).join('') || '<span class="chip">tomada não informada</span>';
const stationCard = s => `<div class="card"><div><h3><a href="${stPath(s)}">${esc(s.name)}</a></h3><div style="color:var(--cinza)">${esc([s.addr, s.city && s.uf ? `${s.city} - ${s.uf}` : ''].filter(Boolean).join(', '))}</div><div style="margin:6px 0">${connChips(s)}</div>
<div style="color:var(--cinza);font-size:.88rem">${[s.op && 'Operador: ' + esc(s.op), s.usage && esc(s.usage), s.hours && 'Horário: ' + esc(s.hours), s.cost && s.cost !== '0' && 'Preço: ' + esc(s.cost)].filter(Boolean).join(' · ')}</div></div>
<a class="btn o s go" href="https://www.google.com/maps/dir/?api=1&destination=${s.lat},${s.lon}">Rota</a></div>`;
const mapScript = (id, geojson, center, zoom, fit) => `<script>(function(){const map=new maplibregl.Map({container:'${id}',style:'https://tiles.openfreemap.org/styles/liberty',center:${JSON.stringify(center)},zoom:${zoom}});map.addControl(new maplibregl.NavigationControl());
map.on('load',()=>{const fc=${geojson};map.addSource('st',{type:'geojson',data:fc,cluster:true,clusterRadius:48,clusterMaxZoom:13});
map.addLayer({id:'cl',type:'circle',source:'st',filter:['has','point_count'],paint:{'circle-color':'#1565C0','circle-radius':['step',['get','point_count'],16,10,20,50,26,200,32],'circle-stroke-width':3,'circle-stroke-color':'#fff'}});
map.addLayer({id:'cn',type:'symbol',source:'st',filter:['has','point_count'],layout:{'text-field':['get','point_count_abbreviated'],'text-size':13,'text-font':['Noto Sans Bold']},paint:{'text-color':'#fff'}});
map.addLayer({id:'pt',type:'circle',source:'st',filter:['!',['has','point_count']],paint:{'circle-color':['case',['get','dc'],'#1565C0','#EF6C00'],'circle-radius':8,'circle-stroke-width':2,'circle-stroke-color':'#fff'}});
map.on('click','cl',e=>{const f=map.queryRenderedFeatures(e.point,{layers:['cl']})[0];map.getSource('st').getClusterExpansionZoom(f.properties.cluster_id,(err,z)=>{if(!err)map.easeTo({center:f.geometry.coordinates,zoom:z})})});
map.on('click','pt',e=>{const p=e.features[0].properties;new maplibregl.Popup().setLngLat(e.features[0].geometry.coordinates).setHTML('<b>'+p.name+'</b><br>'+p.addr+'<br>'+p.conns+'<br><a href="'+p.url+'">Ver eletroposto</a> · <a href="https://www.google.com/maps/dir/?api=1&destination='+p.lat+','+p.lon+'">Rota</a>').addTo(map)});
['cl','pt'].forEach(l=>{map.on('mouseenter',l,()=>map.getCanvas().style.cursor='pointer');map.on('mouseleave',l,()=>map.getCanvas().style.cursor='')});${fit ? `if(fc.features.length>1){const b=new maplibregl.LngLatBounds();fc.features.forEach(f=>b.extend(f.geometry.coordinates));map.fitBounds(b,{padding:40,maxZoom:14})}` : ''}});})();</script>`;
const geo = list => JSON.stringify({ type: 'FeatureCollection', features: list.map(s => ({ type: 'Feature', geometry: { type: 'Point', coordinates: [s.lon, s.lat] }, properties: { name: s.name, addr: [s.addr, s.city, s.uf].filter(Boolean).join(', '), dc: s.dc, conns: s.conns.map(c => c.t + (c.kw ? ' ' + c.kw + ' kW' : '')).join(', ') || 'tomada não informada', lat: s.lat, lon: s.lon, url: stPath(s) } })) });

// ---------- agregados ----------
const byUf = {}; for (const s of stations) (byUf[s.uf] ||= []).push(s);
const dc = stations.filter(s => s.dc).length, cities = new Set(stations.map(s => `${s.uf}|${s.city}`)).size;
const connCount = {}; for (const s of stations) for (const c of s.conns) connCount[c.t] = (connCount[c.t] || 0) + c.q;
const opCount = {}; for (const s of stations) if (s.op) opCount[s.op] = (opCount[s.op] || 0) + 1;
const nets = Object.entries(opCount).filter(([, n]) => n >= 5).sort((a, b) => b[1] - a[1]);
const out = {}; const urls = [];
const add = (file, url, html) => { out[file] = html; urls.push(url); };

// ---------- home ----------
add('index.html', '/', page({ title: 'Eletropostos Brasil – app e mapa de estações de recarga para carros elétricos', desc: `App gratuito com ${fmt(stations.length)} eletropostos em ${Object.keys(byUf).length} estados: mapa, tomadas e potência, planejador de viagem, relatos da comunidade. Sem cadastro.`, path: '/', jsonld: { '@context': 'https://schema.org', '@type': 'MobileApplication', name: 'Eletropostos Brasil', operatingSystem: 'Android', applicationCategory: 'TravelApplication', offers: { '@type': 'Offer', price: '0', priceCurrency: 'BRL' }, author: { '@type': 'Organization', name: 'Spartan TI', url: 'https://spartanti.com.br' } },
  body: `<section class="hero"><div><h1>Onde carregar seu carro elétrico, em qualquer lugar do Brasil</h1><p class="lead">${fmt(stations.length)} eletropostos no mapa, tomadas e potência de cada um, planejador de viagem com paradas de recarga e relatos de quem já carregou.</p>
<div class="badges"><span class="badge">✅ Sem cadastro</span><span class="badge">💸 Grátis</span><span class="badge">📶 Funciona offline</span><span class="badge">🚗 Android Auto</span></div>
<p id="baixar"><a class="btn l" href="${ROOT}/assets/eletropostos-brasil.apk">⚡ Baixar para Android (APK)</a> &nbsp; <a class="btn o" href="${ROOT}/mapa.html">Abrir o mapa</a></p><p style="font-size:.9rem;color:var(--cinza)">Em breve na Google Play. Para instalar o APK, permita "instalar apps desconhecidos" quando o Android pedir.</p></div>
<div class="phone"><img src="${ROOT}/assets/02-mapa-selecionado.png" alt="Tela do app Eletropostos Brasil com o mapa de estações"></div></section>
<section class="stats"><div class="stat"><b>${fmt(stations.length)}</b>eletropostos</div><div class="stat"><b>${fmt(dc)}</b>com recarga rápida (DC)</div><div class="stat"><b>${fmt(cities)}</b>cidades</div><div class="stat"><b>${Object.keys(byUf).length}</b>estados + DF</div></section>
<h2>Tudo o que você precisa para carregar</h2><section class="grid feat">
<div class="card"><div class="ic">📍</div><h3>Mais próximos de você</h3>Lista e mapa ordenados pela distância, com tomada, potência e etiqueta rápida/lenta.</div>
<div class="card"><div class="ic">🟢</div><h3>Funciona ou não?</h3>Relatos da comunidade e status operacional. Um ponto verde ou vermelho no pino diz o que esperar antes de ir.</div>
<div class="card"><div class="ic">🗺️</div><h3>Planejador de viagem</h3>Informe a autonomia do carro e receba as paradas de recarga rápida no caminho. Salve até 3 viagens.</div>
<div class="card"><div class="ic">🚘</div><h3>Meu carro</h3>Escolha o modelo e veja só os eletropostos compatíveis com as suas tomadas.</div>
<div class="card"><div class="ic">🕒</div><h3>Aberto agora e preço</h3>Horário de funcionamento e valor por kWh quando informados.</div>
<div class="card"><div class="ic">➕</div><h3>Cadastre seu ponto</h3>Donos e operadores enviam o eletroposto pelo app ou pelo site; após revisão, aparece para todos.</div></section>
<h2>Como funciona</h2><section class="steps"><div class="step"><h3>Baixe e abra</h3>Sem conta, sem cartão. A base completa já vem no app e atualiza sozinha.</div><div class="step"><h3>Encontre</h3>Veja os mais próximos, filtre por tomada, potência, "aberto agora" ou "meu carro".</div><div class="step"><h3>Vá e conte</h3>Trace a rota pelo Google Maps ou Waze e, depois, relate se funcionou para ajudar os próximos.</div></section>
<h2>Telas do app</h2><div class="shots">${['01-lista', '02-mapa-selecionado', '03-viagem', '04-detalhe', '05-carro', '06-guia'].map(f => `<img loading="lazy" src="${ROOT}/assets/${f}.png" alt="Tela do app Eletropostos Brasil">`).join('')}</div>
<h2>Eletropostos por estado</h2><div class="ufs">${Object.keys(byUf).sort().map(uf => `<a href="${ROOT}/estacoes/${uf.toLowerCase()}/">${UF[uf] || uf} (${fmt(byUf[uf].length)})</a>`).join('')}</div>
<h2>Para operadores, empresas de energia e prefeituras</h2><section class="grid"><div class="card"><h3>Cadastre sua rede</h3>Seus pontos aparecem no app e nas páginas por cidade deste site, com status e link. <a href="${ROOT}/cadastrar.html">Cadastrar</a> ou <a href="mailto:admin@spartanti.com.br">enviar um feed</a>.</div><div class="card"><h3>Inteligência de mercado</h3>Relatórios anônimos de onde falta recarga, picos de demanda e rotas mais planejadas. <a href="${ROOT}/dados.html">Ver dados</a>.</div><div class="card"><h3>Destaque</h3>Quer seu eletroposto em evidência para quem passa pela região? Fale com a Spartan TI.</div></section>` }));

// ---------- mapa ----------
add('mapa.html', '/mapa.html', page({ title: 'Mapa de eletropostos do Brasil – Eletropostos Brasil', desc: `Mapa interativo com ${fmt(stations.length)} estações de recarga para carros elétricos no Brasil, com tomadas e potência.`, path: '/mapa.html', extraHead: MAPLIBRE,
  body: `<h1 style="color:var(--azul2)">Mapa de eletropostos</h1><p>Azul = recarga rápida (DC), laranja = lenta (AC). Toque num ponto para ver tomadas, potência e a página do eletroposto. <a href="${ROOT}/#baixar">No app</a> você tem distância, filtros, relatos e planejador de viagem.</p><div id="map" class="map big"></div>
<script>window.__load=async function(){const d=await (await fetch('${ROOT}/stations.json')).json();return d;}</script>
${mapScript('map', `await (async()=>{const d=await (await fetch('${ROOT}/stations.json')).json();return {type:'FeatureCollection',features:d.stations.map(s=>({type:'Feature',geometry:{type:'Point',coordinates:[s.lon,s.lat]},properties:{name:s.name,addr:[s.addr,s.city,s.uf].filter(Boolean).join(', '),dc:s.dc,conns:s.conns.map(c=>c.t+(c.kw?' '+c.kw+' kW':'')).join(', ')||'tomada não informada',lat:s.lat,lon:s.lon,url:'${ROOT}/estacao/'+(s.city||s.uf).normalize('NFD').replace(/[\\u0300-\\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')+'-'+s.name.normalize('NFD').replace(/[\\u0300-\\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,50)+'-'+s.id.replace(/[^a-z0-9]/gi,'')+'.html'}}))}})()`, [-52, -14.5], 3.6, false).replace("map.on('load',()=>{const fc=", "map.on('load',async()=>{const fc=")}` }));

// ---------- estados, cidades, estações ----------
add('estacoes/index.html', '/estacoes/', page({ title: 'Eletropostos por estado – Eletropostos Brasil', desc: 'Estações de recarga para carros elétricos em cada estado do Brasil, com cidades, tomadas e potência.', path: '/estacoes/', body: `<h1 style="color:var(--azul2)">Eletropostos por estado</h1><p>Escolha o estado para ver as cidades e os eletropostos com tomadas, potência e rota.</p><div class="ufs">${Object.keys(byUf).sort().map(uf => `<a href="${ROOT}/estacoes/${uf.toLowerCase()}/">${UF[uf] || uf} (${fmt(byUf[uf].length)})</a>`).join('')}</div>` }));
for (const uf of Object.keys(byUf).sort()) {
  const list = byUf[uf]; const byCity = {}; for (const s of list) (byCity[s.city || 'Sem cidade'] ||= []).push(s);
  const cities2 = Object.keys(byCity).sort((a, b) => byCity[b].length - byCity[a].length || a.localeCompare(b));
  const ufPath = `/estacoes/${uf.toLowerCase()}/`;
  add(`estacoes/${uf.toLowerCase()}/index.html`, ufPath, page({ title: `Eletropostos em ${UF[uf] || uf}: ${fmt(list.length)} estações de recarga – Eletropostos Brasil`, desc: `Lista de ${fmt(list.length)} eletropostos em ${UF[uf] || uf} (${list.filter(s => s.dc).length} com recarga rápida), por cidade, com tomadas, potência e rota.`, path: ufPath, extraHead: MAPLIBRE,
    jsonld: { '@context': 'https://schema.org', '@type': 'BreadcrumbList', itemListElement: [{ '@type': 'ListItem', position: 1, name: 'Estados', item: `${BASE}/estacoes/` }, { '@type': 'ListItem', position: 2, name: UF[uf] || uf, item: `${BASE}${ufPath}` }] },
    body: `<p class="crumb"><a href="${ROOT}/estacoes/">Estados</a> › ${UF[uf] || uf}</p><h1 style="color:var(--azul2)">Eletropostos em ${UF[uf] || uf}</h1><p>${fmt(list.length)} estações de recarga, ${fmt(list.filter(s => s.dc).length)} com recarga rápida (DC), em ${cities2.length} cidades. <a href="${ROOT}/#baixar">Baixe o app</a> para ver as mais próximas de você.</p>
<div id="map" class="map"></div>${mapScript('map', geo(list), [list[0].lon, list[0].lat], 6, true)}
<h2>Cidades</h2><div class="ufs">${cities2.map(c => `<a href="${ROOT}${ufPath}${slug(c)}.html">${esc(c)} (${byCity[c].length})</a>`).join('')}</div>
<h2>Maiores potências em ${UF[uf] || uf}</h2><div class="grid stlist">${list.filter(s => s.maxkw).sort((a, b) => b.maxkw - a.maxkw).slice(0, 12).map(stationCard).join('')}</div>` }));
  for (const c of cities2) {
    const cs = byCity[c].sort((a, b) => (b.maxkw || 0) - (a.maxkw || 0)); const cp = `${ufPath}${slug(c)}.html`;
    add(`estacoes/${uf.toLowerCase()}/${slug(c)}.html`, cp, page({ title: `Eletropostos em ${c} - ${uf}: ${cs.length} estações de recarga – Eletropostos Brasil`, desc: `Onde carregar carro elétrico em ${c} (${UF[uf] || uf}): ${cs.length} eletropostos com endereço, tomadas (${[...new Set(cs.flatMap(s => s.conns.map(x => x.t)))].join(', ') || 'diversas'}), potência e rota.`, path: cp, extraHead: MAPLIBRE,
      jsonld: { '@context': 'https://schema.org', '@type': 'ItemList', name: `Eletropostos em ${c} - ${uf}`, numberOfItems: cs.length, itemListElement: cs.slice(0, 50).map((s, i) => ({ '@type': 'ListItem', position: i + 1, url: `${BASE}${stPath(s).replace(ROOT, '')}` })) },
      body: `<p class="crumb"><a href="${ROOT}/estacoes/">Estados</a> › <a href="${ROOT}${ufPath}">${UF[uf] || uf}</a> › ${esc(c)}</p><h1 style="color:var(--azul2)">Eletropostos em ${esc(c)} - ${uf}</h1><p>${cs.length} estações de recarga para carros elétricos em ${esc(c)}, ${cs.filter(s => s.dc).length} com recarga rápida. No <a href="${ROOT}/#baixar">app Eletropostos Brasil</a> você vê a distância, se está funcionando e traça a rota.</p>
<div id="map" class="map"></div>${mapScript('map', geo(cs), [cs[0].lon, cs[0].lat], 12, cs.length > 1)}
<div class="grid stlist">${cs.map(stationCard).join('')}</div>` }));
  }
}
// página por eletroposto
for (const s of stations) {
  const near = stations.filter(o => o.id !== s.id).map(o => ({ o, d: km(s, o) })).filter(x => x.d < 30).sort((a, b) => a.d - b.d).slice(0, 5);
  const p = stPath(s).replace(ROOT, '');
  add(p.slice(1), p, page({ title: `${s.name} – eletroposto em ${s.city || UF[s.uf] || s.uf}${s.uf ? ' - ' + s.uf : ''} | Eletropostos Brasil`, desc: `${s.name}: estação de recarga em ${[s.addr, s.city, s.uf].filter(Boolean).join(', ')}. Tomadas: ${s.conns.map(c => c.t + (c.kw ? ' ' + c.kw + ' kW' : '')).join(', ') || 'não informadas'}.${s.op ? ' Operador: ' + s.op + '.' : ''}`, path: p, extraHead: MAPLIBRE,
    jsonld: { '@context': 'https://schema.org', '@type': 'Place', name: s.name, address: { '@type': 'PostalAddress', streetAddress: s.addr, addressLocality: s.city, addressRegion: s.uf, postalCode: s.cep, addressCountry: 'BR' }, geo: { '@type': 'GeoCoordinates', latitude: s.lat, longitude: s.lon }, telephone: s.phone || undefined, url: `${BASE}${p}` },
    body: `<p class="crumb"><a href="${ROOT}/estacoes/">Estados</a> › <a href="${ROOT}/estacoes/${s.uf.toLowerCase()}/">${UF[s.uf] || s.uf}</a> › <a href="${ROOT}/estacoes/${s.uf.toLowerCase()}/${slug(s.city || 'sem-cidade')}.html">${esc(s.city || 'Sem cidade')}</a></p>
<h1 style="color:var(--azul2)">${esc(s.name)}</h1><p style="color:var(--cinza)">${esc([s.addr, s.city && s.uf ? `${s.city} - ${s.uf}` : '', s.cep && 'CEP ' + s.cep].filter(Boolean).join(', '))}</p>
<p><a class="btn" href="https://www.google.com/maps/dir/?api=1&destination=${s.lat},${s.lon}">Traçar rota</a> &nbsp; <a class="btn o" href="https://waze.com/ul?ll=${s.lat},${s.lon}&navigate=yes">Waze</a> &nbsp; <a class="btn l" href="${ROOT}/#baixar">Relatar no app</a></p>
<div class="grid"><div class="card"><h3>Tomadas</h3>${connChips(s)}${s.points ? `<div style="margin-top:6px;color:var(--cinza)">${s.points} ponto(s) de recarga</div>` : ''}</div>
<div class="card"><h3>Informações</h3><table>${[['Operador', s.op], ['Acesso', s.usage], ['Preço', s.cost && s.cost !== '0' ? s.cost : ''], ['Horário', s.hours], ['Telefone', s.phone], ['Site', s.url ? `<a href="${esc(s.url)}">${esc(s.url.replace(/^https?:\/\//, '').slice(0, 40))}</a>` : ''], ['Status', s.operational === false ? 'Registrado como fora de operação' : s.status], ['Fonte', s.src === 'osm' ? 'OpenStreetMap' : s.src === 'spartanti' ? 'Cadastro no app' : 'Open Charge Map'], ['Atualizado', s.updated]].filter(([, v]) => v).map(([k, v]) => `<tr><th>${k}</th><td>${k === 'Site' ? v : esc(v)}</td></tr>`).join('')}</table></div></div>
<div id="map" class="map"></div>${mapScript('map', geo([s, ...near.map(x => x.o)]), [s.lon, s.lat], 14, false)}
${near.length ? `<h2>Eletropostos próximos</h2><div class="grid stlist">${near.map(x => stationCard(x.o).replace('</h3>', ` <small style="color:var(--cinza)">(${x.d.toFixed(1)} km)</small></h3>`)).join('')}</div>` : ''}
${s.notes ? `<h2>Observações</h2><p>${esc(s.notes)}</p>` : ''}
<p style="color:var(--cinza);font-size:.9rem">Informação errada ou eletroposto desativado? <a href="${ROOT}/#baixar">Relate no app</a> ou <a href="mailto:admin@spartanti.com.br?subject=Corre%C3%A7%C3%A3o%20${encodeURIComponent(s.name)}">envie uma correção</a>.</p>` }));
}

// ---------- redes ----------
add('redes/index.html', '/redes/', page({ title: 'Redes e operadores de recarga no Brasil – Eletropostos Brasil', desc: 'Quais redes operam eletropostos no Brasil e quantos pontos cada uma tem na base aberta.', path: '/redes/', body: `<h1 style="color:var(--azul2)">Redes e operadores</h1><p>Operadores com 5 ou mais pontos na base. Sua rede não está aqui ou está incompleta? <a href="mailto:admin@spartanti.com.br">Envie seu feed</a>.</p><table><tr><th>Rede</th><th>Eletropostos</th><th>Com DC</th></tr>${nets.map(([o, n]) => `<tr><td><a href="${ROOT}/redes/${slug(o)}.html">${esc(o)}</a></td><td>${n}</td><td>${stations.filter(s => s.op === o && s.dc).length}</td></tr>`).join('')}</table>` }));
for (const [o, n] of nets) {
  const list = stations.filter(s => s.op === o); const p = `/redes/${slug(o)}.html`;
  add(p.slice(1), p, page({ title: `${o}: ${n} eletropostos no Brasil – Eletropostos Brasil`, desc: `Onde estão os ${n} pontos de recarga da rede ${o}, com cidades, tomadas e potência.`, path: p, extraHead: MAPLIBRE, body: `<p class="crumb"><a href="${ROOT}/redes/">Redes</a> › ${esc(o)}</p><h1 style="color:var(--azul2)">${esc(o)}</h1><p>${n} eletropostos, ${list.filter(s => s.dc).length} com recarga rápida, em ${new Set(list.map(s => s.city)).size} cidades.</p><div id="map" class="map"></div>${mapScript('map', geo(list), [list[0].lon, list[0].lat], 5, true)}<div class="grid stlist">${list.sort((a, b) => (b.maxkw || 0) - (a.maxkw || 0)).slice(0, 60).map(stationCard).join('')}</div>` }));
}

// ---------- guia, faq, dados, cadastrar ----------
add('guia-tomadas.html', '/guia-tomadas.html', page({ title: 'Guia de tomadas e tipos de carregamento de carro elétrico – Eletropostos Brasil', desc: 'AC e DC, faixas de potência em kW e cada conector explicado: Tipo 2, CCS2, CHAdeMO, GB/T, Tipo 1, CCS1, Tesla, tomada industrial e comum.', path: '/guia-tomadas.html', body: `<h1 style="color:var(--azul2)">Guia de tomadas e carregamento</h1>
<div class="grid"><div class="card" style="border-left:6px solid var(--laranja)"><h3>Lenta (AC) – corrente alternada</h3>A energia entra em corrente alternada e o próprio carro a converte. A velocidade fica limitada ao carregador de bordo (em geral 7 ou 11 kW). Recarga completa em 4 a 10 horas: casa, trabalho, shopping e hotel.</div><div class="card" style="border-left:6px solid var(--azul)"><h3>Rápida (DC) – corrente contínua</h3>A estação converte a energia e entrega direto na bateria, com 30 a 350 kW. De 10% a 80% em 20 a 50 minutos. Recarga de viagem, em rodovias e postos.</div></div>
<h2>Faixas de potência</h2><table><tr><th>Potência</th><th>Tipo</th><th>O que esperar</th></tr><tr><td>até 7,4 kW</td><td>lento (AC)</td><td>cerca de 30 a 40 km de autonomia por hora</td></tr><tr><td>11 a 22 kW</td><td>semirrápido (AC trifásico)</td><td>60 a 120 km por hora</td></tr><tr><td>30 a 60 kW</td><td>rápido (DC)</td><td>10% a 80% em cerca de 1 hora</td></tr><tr><td>100 a 150 kW</td><td>rápido (DC)</td><td>10% a 80% em 30 a 40 minutos</td></tr><tr><td>acima de 150 kW</td><td>ultrarrápido (DC)</td><td>10% a 80% em menos de 30 minutos</td></tr></table><p style="color:var(--cinza)">O kW indicado é o máximo da estação; o carro só recebe o que aceita, e a velocidade cai quando a bateria passa de 80%.</p>
<h2>Conectores</h2><div class="grid">${[['Tipo 2 (Mennekes)', 'AC', 'Padrão brasileiro (ABNT NBR IEC 62196) para recarga lenta e semirrápida, até 22 kW. Praticamente todos os elétricos vendidos no Brasil.'], ['CCS2 (Combo 2)', 'DC', 'Padrão brasileiro de recarga rápida: o encaixe do Tipo 2 mais dois pinos DC, de 50 a 350 kW. BYD, GWM, Volvo, BMW, Renault, Porsche e outros.'], ['CHAdeMO', 'DC', 'Padrão japonês, até 50 kW (raramente 100). Nissan Leaf e alguns híbridos plug-in antigos. Em desuso.'], ['GB/T', 'AC/DC', 'Padrão chinês. No Brasil aparece em JAC antigos e alguns ônibus e caminhões; os chineses vendidos hoje (BYD, GWM) usam Tipo 2 e CCS2.'], ['Tipo 1 (J1772)', 'AC', 'Padrão americano/japonês monofásico, até 7,4 kW. Importados antigos (Leaf 1ª geração, Outlander PHEV). Existem adaptadores para Tipo 2.'], ['CCS1', 'DC', 'Versão americana do CCS. Raro no Brasil (Bolt importado).'], ['Tesla', 'AC/DC', 'Conector proprietário (NACS nos EUA). No Brasil os Tesla usam Tipo 2/CCS2 ou adaptador; carregadores de destino Tesla existem em hotéis.'], ['Industrial (CEE/IEC 60309)', 'AC', 'Tomada industrial azul (monofásica) ou vermelha (trifásica), 3,7 a 22 kW. Exige carregador portátil com plugue industrial. Comum em pousadas e sítios.'], ['Tomada comum (NBR 14136)', 'AC', 'Tomada de parede, 1,3 a 2,2 kW (10 ou 20 A). Carregador portátil de emergência; uma noite rende 100 a 150 km. Use circuito dedicado.']].map(([n, t, d]) => `<div class="card"><h3>${n} <span class="tag ${t.includes('DC') ? '' : 'ac'}">${t}</span></h3>${d}</div>`).join('')}</div>` }));
add('perguntas-frequentes.html', '/perguntas-frequentes.html', page({ title: 'Perguntas frequentes – Eletropostos Brasil', desc: 'Dúvidas sobre o app Eletropostos Brasil: cadastro, dados, relatos, planejador de viagem, privacidade.', path: '/perguntas-frequentes.html', jsonld: { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: [['Preciso criar conta?', 'Não. O app funciona sem cadastro, sem cartão e sem saldo. Para carregar, você usa o app da rede do eletroposto, se ela exigir.'], ['O ponto está funcionando?', 'Veja o ponto colorido no pino e a linha "Confirmado funcionando" na ficha. Um status só aparece quando mais de 5 motoristas relatam o mesmo.'], ['De onde vêm os dados?', 'Open Charge Map, OpenStreetMap, cadastros feitos no app e status do Carregados, com atualização semanal e download automático.'], ['O planejador considera meu carro?', 'Sim: escolha o modelo em Mais → Meu carro e informe a autonomia real. Ele sugere paradas de recarga rápida compatíveis.'], ['Como remover meus dados?', 'O app não guarda dados pessoais em servidor. Relatos e cadastros podem ser removidos por e-mail. Estatísticas anônimas podem ser desligadas em Mais.']].map(([q, a]) => ({ '@type': 'Question', name: q, acceptedAnswer: { '@type': 'Answer', text: a } })) },
  body: `<h1 style="color:var(--azul2)">Perguntas frequentes</h1>${[['Preciso criar conta?', 'Não. O app funciona sem cadastro, sem cartão e sem saldo. Para carregar, você usa o app da rede do eletroposto, se ela exigir.'], ['O ponto está funcionando?', 'Veja o ponto colorido no pino e a linha "Confirmado funcionando" na ficha. Um status só aparece quando mais de 5 motoristas relatam o mesmo. Ajude relatando depois de carregar.'], ['De onde vêm os dados?', 'Open Charge Map, OpenStreetMap, cadastros feitos no app e status operacional do Carregados, com atualização semanal e download automático. Preço e horário aparecem quando a base informa.'], ['O planejador considera meu carro?', 'Sim: escolha o modelo em Mais → Meu carro e informe a autonomia real. Ele sugere paradas de recarga rápida compatíveis, carregando até 80% em cada uma, e ignora pontos desativados ou com problema confirmado.'], ['O app tem anúncios?', 'Sim, um banner discreto do Google que mantém o app gratuito. Não há cadastro nem venda de dados pessoais.'], ['Como cadastro meu eletroposto?', 'Pelo app (Mais → Cadastrar eletroposto) ou pela página Cadastrar deste site. Após revisão da Spartan TI, o ponto aparece para todos.'], ['Como remover meus dados?', 'O app não guarda dados pessoais em servidor. Relatos e cadastros podem ser removidos pelo e-mail admin@spartanti.com.br. Estatísticas anônimas podem ser desligadas em Mais.']].map(([q, a]) => `<details open><summary>${q}</summary><p>${a}</p></details>`).join('')}` }));
add('dados.html', '/dados.html', page({ title: 'Dados do mercado de recarga de carros elétricos no Brasil – Eletropostos Brasil', desc: 'Quantos eletropostos existem por estado, quais tomadas dominam, participação de recarga rápida e principais operadores, a partir de bases abertas.', path: '/dados.html',
  body: `<h1 style="color:var(--azul2)">Dados do mercado de recarga</h1><p>Números da base aberta do Eletropostos Brasil em ${data.generated} (Open Charge Map + OpenStreetMap + cadastros no app). Relatórios de demanda anônima (áreas com falta de recarga, picos e rotas) estão disponíveis para empresas de energia, operadores e prefeituras: <a href="mailto:admin@spartanti.com.br">fale com a Spartan TI</a>.</p>
<section class="stats"><div class="stat"><b>${fmt(stations.length)}</b>eletropostos</div><div class="stat"><b>${(100 * dc / stations.length).toFixed(0)}%</b>com recarga rápida</div><div class="stat"><b>${fmt(Object.values(connCount).reduce((a, b) => a + b, 0))}</b>tomadas</div><div class="stat"><b>${fmt(cities)}</b>cidades</div></section>
<h2>Por estado</h2><table><tr><th>Estado</th><th>Eletropostos</th><th>Com DC</th><th>% DC</th></tr>${Object.keys(byUf).sort((a, b) => byUf[b].length - byUf[a].length).map(uf => `<tr><td><a href="${ROOT}/estacoes/${uf.toLowerCase()}/">${UF[uf] || uf}</a></td><td>${fmt(byUf[uf].length)}</td><td>${fmt(byUf[uf].filter(s => s.dc).length)}</td><td>${(100 * byUf[uf].filter(s => s.dc).length / byUf[uf].length).toFixed(0)}%</td></tr>`).join('')}</table>
<h2>Tomadas</h2><table><tr><th>Tipo</th><th>Quantidade</th></tr>${Object.entries(connCount).sort((a, b) => b[1] - a[1]).map(([t, n]) => `<tr><td>${esc(t)}</td><td>${fmt(n)}</td></tr>`).join('')}</table>
<h2>Operadores com mais pontos</h2><table><tr><th>Operador</th><th>Eletropostos</th></tr>${nets.slice(0, 25).map(([o, n]) => `<tr><td><a href="${ROOT}/redes/${slug(o)}.html">${esc(o)}</a></td><td>${fmt(n)}</td></tr>`).join('')}</table>` }));
const inp = (n, l, extra = '') => `<label>${l}<br><input name="${n}" ${extra} style="width:100%;padding:10px;border:1px solid #C9D3E0;border-radius:8px"></label>`;
add('cadastrar.html', '/cadastrar.html', page({ title: 'Cadastre seu eletroposto – Eletropostos Brasil', desc: 'Donos e operadores de pontos de recarga: cadastre gratuitamente e apareça no app e no site.', path: '/cadastrar.html',
  body: `<h1 style="color:var(--azul2)">Cadastre seu eletroposto</h1><p>Gratuito. Após uma revisão rápida da Spartan TI, o ponto aparece no app para todos os usuários e nas páginas por cidade deste site.</p>
<form id="f" class="card" style="max-width:720px">${inp('name', 'Nome do local *', 'required')}<br><br>${inp('addr', 'Endereço')}<br><br><div style="display:grid;grid-template-columns:2fr 1fr;gap:10px">${inp('city', 'Cidade')}${inp('uf', 'UF', 'maxlength="2"')}</div><br>
<div style="display:grid;grid-template-columns:1fr 1fr;gap:10px">${inp('lat', 'Latitude *', 'required placeholder="-20.3155"')}${inp('lon', 'Longitude *', 'required placeholder="-40.2986"')}</div><small>No Google Maps, toque e segure no local e copie as coordenadas.</small><br><br>
<div style="display:grid;grid-template-columns:2fr 1fr 1fr;gap:10px"><label>Tomada *<br><select name="t" style="width:100%;padding:10px;border-radius:8px"><option>CCS2</option><option>Tipo 2</option><option>CHAdeMO</option><option>GB/T</option><option>Tipo 1</option><option>Tesla</option><option>Industrial</option><option>Tomada</option></select></label>${inp('kw', 'kW')}${inp('q', 'Quantidade', 'value="1"')}</div><br>
${inp('op', 'Operador / rede')}<br><br><div style="display:grid;grid-template-columns:1fr 1fr;gap:10px">${inp('cost', 'Preço (ex.: R$ 2,49/kWh)')}${inp('hours', 'Horário (ex.: 24/7)')}</div><br>${inp('contact', 'Seu contato (opcional)')}<br><br>
<button class="btn" type="submit">Enviar cadastro</button> <span id="msg" style="margin-left:10px"></span></form>
<p>Prefere o app? Em <b>Mais → Cadastrar eletroposto</b> você usa a localização do celular. Ou fale no WhatsApp <a href="https://wa.me/5527992557140">+55 27 99255-7140</a>. Redes com muitos pontos: envie um feed (CSV, JSON ou OCPI) para <a href="mailto:admin@spartanti.com.br">admin@spartanti.com.br</a>.</p>
<script>document.getElementById('f').addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.target);const b={name:f.get('name'),addr:f.get('addr'),city:f.get('city'),uf:(f.get('uf')||'').toUpperCase(),lat:parseFloat(String(f.get('lat')).replace(',','.')),lon:parseFloat(String(f.get('lon')).replace(',','.')),conns:[{t:f.get('t'),kw:parseFloat(String(f.get('kw')).replace(',','.'))||null,q:parseInt(f.get('q'))||1}],op:f.get('op'),cost:f.get('cost'),hours:f.get('hours'),contact:f.get('contact'),device:'site'};const m=document.getElementById('msg');m.textContent='Enviando…';try{const r=await fetch('${API}/api/submissions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(b)});const j=await r.json();m.textContent=r.ok?'✅ '+j.message:'⚠️ '+(j.error||'erro');if(r.ok)e.target.reset()}catch(err){m.textContent='⚠️ Não foi possível enviar. Tente pelo app ou WhatsApp.'}});</script>` }));

// ---------- sitemap / robots / CNAME ----------
out['sitemap.xml'] = `<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${urls.map(u => `<url><loc>${BASE}${u}</loc><lastmod>${today}</lastmod></url>`).join('')}</urlset>`;
out['robots.txt'] = `User-agent: *\nAllow: /\nSitemap: ${BASE}/sitemap.xml\n`;
if (DOMAIN) out['CNAME'] = DOMAIN + '\n'; else if (fs.existsSync('CNAME')) fs.unlinkSync('CNAME');
fs.rmSync('estacao', { recursive: true, force: true }); fs.rmSync('estacoes', { recursive: true, force: true }); fs.rmSync('redes', { recursive: true, force: true });
for (const [f, c] of Object.entries(out)) { fs.mkdirSync(f.includes('/') ? f.slice(0, f.lastIndexOf('/')) : '.', { recursive: true }); fs.writeFileSync(f, c); }
console.log(`site gerado: ${Object.keys(out).length} arquivos, ${urls.length} URLs no sitemap, domínio ${DOMAIN || '(GitHub Pages)'}`);
